= SVGBuilder

== Point, vector, size, displacement
https://gamedev.stackexchange.com/questions/44314/do-i-need-a-point-and-a-vector-object-or-just-using-a-vector-object-to-represen
A size is positive.
A point (as an SVG coordinate in a coordinate system that starts at zero) is positive.
A displacement (mathematically corresponding to a vector) is not necessarily positive.

Currently, I have:
MathSize anything [DoubleVector]
PositiveSize implements MathSize. [DoublePoint]
GeneralSize implements MathSize. Unused? [DoubleDisplacement]
DoublePoint, anything [DoubleDisplacement]

I should have:
Vector (unspecified): IntVector, DoubleVector
Displacement (anything): IntDisplacement, DoubleDisplacement. Implements Vector.
Size or point (positive): IntPoint, DoublePoint. Implements Vector.

Vector moveBy(vector) guaranteed only if result is positive.
Point plus displacement/point is a point (moveBy).
Displacement plus point/displacement is a displacement (moveBy).

== About SVG 2
From https://stackoverflow.com/q/26088839/: “ Asking if a browser supports SVG 2 is like asking if a browser supports HTML5. It seems like a totally reasonable question, but it doesn't work like that. The best we can do is test if a browser supports a feature, rather than a version of spec. ” Jan 2016: “Browsers are implementing individual features as the spec stabilizes and interest exists, they are not waiting to implement "SVG 2" all at once.” https://github.com/Fyrd/caniuse/issues/1143 Nov 2016: “SVG 2 is on life support.” http://tavmjong.free.fr/svg2_status.html May 2018: “After a near death experience, SVG 2 is back.”, https://www.patreon.com/posts/svg-2-status-19078074, Tavmjong Bah Sep 2022: “It seems chromium suppports ~40-50% of SVG 2 which is huge and enable many impacting usecases.” https://github.com/Fyrd/caniuse/issues/1143#issuecomment-1233975910 Jan 2023: some features of SVG 2 work, but nobody seem to know which ones. https://cloudfour.com/thinks/so-you-can-set-an-svg-circles-radius-in-css/ March 2023: https://svgwg.org/svg2-draft/ (but the three commits of 2023 are one line each, https://github.com/w3c/svgwg/commits/main/) https://github.com/Fyrd/caniuse/issues/1143 We follow MDN (eg do not use version and baseProfile attributes, “Both version and baseProfile attributes are deprecated in SVG 2”, https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Getting_Started).

== TODO
Implement SVG1 DOM and https://svgwg.org/svg2-draft/types.html#InterfaceSVGElement[SVG2 DOM] and in particular getBBox.

== Batik and SVG DOM 1.0
SVG 1.0 (2001) DOM: https://www.w3.org/TR/SVG10/java.html[Java binding] (https://stackoverflow.com/a/48388117/[thanks]).

Batik 1.9 https://stackoverflow.com/a/48388117/[reportedly] depends on SVG DOM 1.0.
Should check whether more recent https://central.sonatype.com/artifact/org.apache.xmlgraphics/batik/versions[Batik] also do.

Batik 1.17 https://xmlgraphics.apache.org/batik/download.html[bin] contains a lib `xml-apis-ext-1.3.04.jar` containing `org/w3c/dom/smil` and `org/w3c/dom/svg`. https://stackoverflow.com/a/48388117/[Most probably] SVG 1.0. Most probably also in Maven central (but I did not check). Needs to be package-relocated before use anyway.

https://xmlgraphics.apache.org/batik/using/scripting/java.html (might include batik-all or some similar stuff, to get SVG 1.0, to get the BBox): https://stackoverflow.com/questions/34078251/getbbox-for-embedded-svg-element-with-batik

In Batik, see perhaps BBox on SVGSVGElement or SVGLocatable or such.

Also perhaps https://stackoverflow.com/questions/30092651/where-has-org-apache-batik-dom-svg-svgdomimplementation-gone[this] and https://stackoverflow.com/a/63571697/[this] may be useful.

== SVG DOM 1.1
https://www.w3.org/TR/SVG11/java.html[SVG 1.1 (2011) DOM]

Reportedly differs from 1.0, for example org.w3c.dom.svg.SVGTransformList.getNumberOfItems went from int to long (https://stackoverflow.com/a/48388117/[thanks]).

Consider using (or modifying) https://central.sonatype.com/artifact/org.axsl.org.w3c.dom.svg/svg-dom-java[aXSL] (see their https://sourceforge.net/p/axsl/code/HEAD/tree/trunk/svg-dom/src/main/resources/readme.txt[explanation] and (empty) https://www.javadoc.io/doc/org.axsl.org.w3c.dom.svg/svg-dom-java/latest/index.html[javadoc]).
There’s a few problems. 
The https://sourceforge.net/p/axsl/code/HEAD/tree/trunk/svg-dom/src/main/java/org/w3c/dom/svg/[package] should specify that it is SVG1.1 so as to distinguish the interfaces from their 2 counterpart.
There is no implementation!

== SVG DOM 2

== More links
“https://www.javadoc.io/doc/org.apache.xmlgraphics/xmlgraphics-commons/latest/index.html[Apache XML Graphics Commons] is a library in which the two XML Graphics subprojects (Apache Batik and Apache FOP) extracted components which are used by both codebases”.

Fails for https://www.javadoc.io/doc/org.apache.xmlgraphics/batik-all/latest/index.html[batik-all] or similar.

== Vrac
  /**
   * Creates a new SVG DOM Document, containing only the SVG document element.
   *
   * @return a new {@code Document} object with a document element having namespace
   *         {@link #SVG_NS_URI} and name “{@code svg}”.
   */
  public Document svg() {
    /*
     * if https://issues.apache.org/jira/browse/BATIK-1325[] ever gets implemented, we could even
     * return an SVGDocument here (though that doesn’t seem useful, after all).
     */
    return createDocument(SVG_NS_URI.toString(), "svg");
  }

